MovBundle\Entity\Commentaires:
    type: entity
    table: null
    repositoryClass: MovBundle\Repository\CommentairesRepository
    id:
        id:
            type: integer
            id: true
            generator:
                strategy: AUTO
    fields:
        created_at:
            type: datetime
    lifecycleCallbacks: {  }
    manyToOne:
        texte:
            targetEntity: MovBundle\Entity\Photos
            inversedBy: comments