homepage:
    path:     /
    defaults: { _controller: MovBundle:Moza:index }

upload:
    path:     /upload
    defaults: { _controller: MovBundle:Upload:new }

map:
    path:     /map
    defaults: { _controller: MovBundle:Map:index }

homepage_sendMail:
    path: /sendMail
    defaults: {_controller: MovBundle:Default:sendMail }

patrimoine_mail:
    path: /mail
    defaults: {_controller: MovBundle:Default:mail }
